### ISSUE TITLE
Keyboard shortcut don't work on 0.7.2

### ISSUE THREAD

**Issue by jmatsushita** [bfabry/workspace-nav#7]
Things seem to work when using the plugin from the command menu but the keyboard shortcut don't work. In addition I sometimes see the following error in the console (when using navigate down or up).

```
Invalid behavior: :lt.objs.sidebar.command/exec-command
Error: No protocol method IDeref.-deref defined for type null: 
    at Error (<anonymous>)
    at cljs.core.missing_protocol (file:///Users/jun/Downloads/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:1460:10)
    at cljs.core._deref (file:///Users/jun/Downloads/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:2181:38)
    at cljs.core.deref (file:///Users/jun/Downloads/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:12879:27)
    at lt.object.__GT_content (file:///Users/jun/Downloads/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:20727:119)
    at set_selected_class (/Users/jun/Library/Application%20Support/LightTable/plugins/Workspace_Nav/workspace%20nav_compiled.js:37:131)
    at eval (/Users/jun/Library/Application%20Support/LightTable/plugins/Workspace_Nav/workspace%20nav_compiled.js:141:45)
    at Function.b (file:///Users/jun/Downloads/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:8071:176)
    at cljs.core.apply_to (file:///Users/jun/Downloads/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:6105:48)
    at c (file:///Users/jun/Downloads/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:6194:66)
```

**Comment by kenny-evitt** [comment]
I'm seeing this too on a build of the latest LT source too.

**Comment by christopherbalz** [comment]
I see this on 0.7.2 as well.
